vim.opt.guicursor = "i:ver25"
vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.colorcolumn = "80"
vim.opt.winborder = "rounded"
vim.opt.clipboard = "unnamedplus"
vim.opt.listchars = "tab:> ,multispace:|"
vim.g.mapleader = " "
